[phases.setup]
nixPkgs = ["php84", "php84Packages.composer", "nodejs"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader", "npm install", "npm run build"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
