[build]
builder = "NIXPACKS"

[deploy]
preDeployCommand = "php artisan config:clear && php artisan migrate --force && php artisan db:seed --force"
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
